FROM mcr.microsoft.com/devcontainers/javascript-node:0-20

# Install any additional tools you might need
# For example:
# RUN apt-get update && apt-get install -y some-package

# Set the working directory
WORKDIR /workspace

# The jsonhero-web clone and npm install will be done by postCreateCommand in devcontainer.json